/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Menu.java
 *
 * Created on Dec 31, 2017, 8:24:38 PM
 */

/**
 *
 * @author user
 */
public class Menu extends javax.swing.JFrame {

//Global Variables
    String ID;
    /** Creates new form Menu */
    public Menu() {
        initComponents();
    }
    public Menu(String id) {
        initComponents();
        ID = id;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JavaRB = new javax.swing.JRadioButton();
        HtmlRB = new javax.swing.JRadioButton();
        DbmsRB = new javax.swing.JRadioButton();
        NetworkingRB = new javax.swing.JRadioButton();
        Start = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select Your Subject");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 26));
        jLabel1.setText("WELCOME TO COOL QUIZ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setText("SELECT YOUR SUBJECT");

        JavaRB.setFont(new java.awt.Font("Tahoma", 1, 14));
        JavaRB.setText("JAVA");

        HtmlRB.setFont(new java.awt.Font("Tahoma", 1, 14));
        HtmlRB.setText("HTML");

        DbmsRB.setFont(new java.awt.Font("Tahoma", 1, 14));
        DbmsRB.setText("DBMS");

        NetworkingRB.setFont(new java.awt.Font("Tahoma", 1, 14));
        NetworkingRB.setText("NETWORKING");

        Start.setFont(new java.awt.Font("Tahoma", 1, 14));
        Start.setText("START TEST >>");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel2)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JavaRB)
                            .addComponent(DbmsRB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(HtmlRB)
                            .addComponent(NetworkingRB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Start)))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JavaRB)
                    .addComponent(HtmlRB))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DbmsRB)
                    .addComponent(NetworkingRB))
                .addGap(28, 28, 28)
                .addComponent(Start, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        // TODO add your handling code here:
        String sub = null;
        if(JavaRB.isSelected())
            sub = "java";
        else if(HtmlRB.isSelected())
            sub = "html";
        else if(DbmsRB.isSelected())
            sub = "dbms";
        else if(NetworkingRB.isSelected())
            sub = "networking";
        if (sub != null)
        {
            Test t = new Test(sub,ID);
            t.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_StartActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DbmsRB;
    private javax.swing.JRadioButton HtmlRB;
    private javax.swing.JRadioButton JavaRB;
    private javax.swing.JRadioButton NetworkingRB;
    private javax.swing.JButton Start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
